# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project25_Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # Pods for testing
    pod 'Alamofire'
    pod 'JGProgressHUD'
    pod 'Toast-Swift'
  # Pods for Project25_Weather

  target 'Project25_WeatherTests' do
    inherit! :search_paths
  end

end
